name: NPM Release and Publish

on:
  push:
    branches:
      - "main"

jobs:
  quality-bump-and-publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci-skip]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
      - name: Install npm dependencies
        run: npm ci
      - name: Run quality checks
        run: npm run quality
      - name: Build project
        run: npm run build
      - name: Prevent husky from interfering with standard-version commit
        run: rm ./.git/hooks/prepare-commit-msg
      - name: Run standard-version to bump version
        run: npm run release
      - name: Push version bump to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
          force: true
      - name: Bundle tarball
        run: npm run package
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
